### ISSUE TITLE
índice de casos

### ISSUE THREAD

**Issue by escalope** [Melkoroth/AIDEdevelopment#1]
Debería haber una página adicional con el índice de casos. Ahora está en el title bar. Que ponga Case 1 y Case 2 no ayuda a elegir cuál abrir

**Comment by jlpdiez** [comment]
Fixed
http://grasiagroup.fdi.ucm.es/aidendd/cases-list-1-10/
http://grasiagroup.fdi.ucm.es/aidendd/cases-list-11-20/
